# Generated by Django 6.0.5 on 2026-05-25 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP'), ('UTILITY', 'UTILITY'), ('TRAVEL', 'TRAVEL')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('SCOPE1', 'Scope 1'), ('SCOPE2', 'Scope 2'), ('SCOPE3', 'Scope 3')], max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('activity_value', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('normalized_value', models.FloatField()),
                ('normalized_unit', models.CharField(max_length=50)),
                ('suspicious', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('LOCKED', 'Locked')], default='PENDING_REVIEW', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.emissionrecord')),
            ],
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_json', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('VALID', 'VALID'), ('FAILED', 'FAILED')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.datasource')),
            ],
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='source_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rawrecord'),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
    ]
